// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230706082925_second migration")]
    partial class secondmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "MOTOROLA",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6736),
                            DetailName = "Celular Motorola Moto G13\"",
                            Price = 500,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6746)
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6747),
                            DetailName = "Televisor LG LED 50\"",
                            Price = 1000,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6748)
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6749),
                            DetailName = "Televisor LG LED 55\"",
                            Price = 1199,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6749)
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "SAMSUNG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6750),
                            DetailName = "Celular Samsung Galaxy A24",
                            Price = 949,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6751)
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "LENOVO",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6752),
                            DetailName = "Laptop Lenovo IdeaPad Gaming 3i 15.6\"",
                            Price = 2000,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "SONY",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6753),
                            DetailName = "Consola Playstation 5",
                            Price = 2400,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6754)
                        },
                        new
                        {
                            Id = 7,
                            BrandName = "SONY",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6755),
                            DetailName = "Consola Playstation 4",
                            Price = 1500,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6755)
                        },
                        new
                        {
                            Id = 8,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6756),
                            DetailName = "Phone 13 128GB Azul",
                            Price = 3229,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 9,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6757),
                            DetailName = "Phone 12 128GB Azul",
                            Price = 2999,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6758)
                        },
                        new
                        {
                            Id = 10,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6759),
                            DetailName = "Phone 11 128GB Azul",
                            Price = 1549,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Id = 11,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6760),
                            DetailName = "Televisor SONY 65\"",
                            Price = 3000,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6760)
                        },
                        new
                        {
                            Id = 12,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6761),
                            DetailName = "Apple AirPods 3ra Gen",
                            Price = 699,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            Id = 13,
                            BrandName = "SAMSUNG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6763),
                            DetailName = "Celular Samsung Galaxy A73 ",
                            Price = 1699,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            Id = 14,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6764),
                            DetailName = "Televisor LG LED 50\"",
                            Price = 999,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            Id = 15,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6765),
                            DetailName = "Televisor LG LED 60\"",
                            Price = 1899,
                            UpdateDate = new DateTime(2023, 7, 6, 3, 29, 25, 705, DateTimeKind.Local).AddTicks(6766)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
