// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230706015650_First Migrations")]
    partial class FirstMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "MOTOROLA",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3085),
                            DetailName = "Celular Motorola Moto G13\"",
                            Price = 500,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3094)
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3096),
                            DetailName = "Televisor LG LED 50\"",
                            Price = 949,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3096)
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3097),
                            DetailName = "Televisor LG LED 55\"",
                            Price = 1199,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3098)
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "SAMSUNG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3099),
                            DetailName = "Celular Samsung Galaxy A24",
                            Price = 949,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "LENOVO",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3100),
                            DetailName = "Laptop Lenovo IdeaPad Gaming 3i 15.6\"",
                            Price = 949,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3100)
                        },
                        new
                        {
                            Id = 6,
                            BrandName = "SONY",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3101),
                            DetailName = "Consola Playstation 5",
                            Price = 949,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3101)
                        },
                        new
                        {
                            Id = 7,
                            BrandName = "SONY",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3102),
                            DetailName = "Consola Playstation 4",
                            Price = 1500,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3103)
                        },
                        new
                        {
                            Id = 8,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3104),
                            DetailName = "Phone 13 128GB Azul",
                            Price = 3229,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3104)
                        },
                        new
                        {
                            Id = 9,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3105),
                            DetailName = "Phone 12 128GB Azul",
                            Price = 2999,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3105)
                        },
                        new
                        {
                            Id = 10,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3106),
                            DetailName = "Phone 11 128GB Azul",
                            Price = 1549,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3107)
                        },
                        new
                        {
                            Id = 11,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3107),
                            DetailName = "Televisor LG 65\"",
                            Price = 1549,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3108)
                        },
                        new
                        {
                            Id = 12,
                            BrandName = "APPLE",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3109),
                            DetailName = "Apple AirPods 3ra Gen",
                            Price = 699,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3109)
                        },
                        new
                        {
                            Id = 13,
                            BrandName = "SAMSUNG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3110),
                            DetailName = "Celular Samsung Galaxy A73 ",
                            Price = 1699,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3110)
                        },
                        new
                        {
                            Id = 14,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3111),
                            DetailName = "Televisor LG LED 50\"",
                            Price = 999,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3112)
                        },
                        new
                        {
                            Id = 15,
                            BrandName = "LG",
                            CreateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3112),
                            DetailName = "Televisor LG LED 60\"",
                            Price = 1899,
                            UpdateDate = new DateTime(2023, 7, 5, 20, 56, 50, 717, DateTimeKind.Local).AddTicks(3113)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
